OLED_ENABLE = yes
OLED_DRIVER = ssd1306   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
WPM_ENABLE = yes # Enable words per minute calculation
EXTRAFLAGS += -flto
CONSOLE_ENABLE = no
SLEEP_LED_ENABLE = yes
TERMINAL_ENABLE = no
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
